/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v13.0
processor: MKE02Z64xxx4
package_id: MKE02Z64VLH4
mcu_data: ksdk2_0
processor_version: 13.0.1
board: FRDM-KE02Z40M
external_user_signals: {}
pin_labels:
- {pin_num: '16', pin_signal: PTE6, label: 'J1[13]'}
- {pin_num: '26', pin_signal: PTC0/FTM2_CH0/ADC0_SE8, label: 'J10[4]', identifier: Start_Calda}
- {pin_num: '27', pin_signal: PTF7/ADC0_SE15, label: 'J2[9]/J10[2]/PTF7_A0_ANA0', identifier: Start_Fredda}
- {pin_num: '42', pin_signal: PTF1, label: 'J9[11]', identifier: Led_1_Ora}
- {pin_num: '43', pin_signal: PTF0, label: 'J9[13]', identifier: Led_2_Ora}
- {pin_num: '46', pin_signal: PTD2/KBI1_P2/SPI1_MISO, label: 'J9[9]', identifier: Pulsante}
- {pin_num: '53', pin_signal: PTE3/SPI0_PCS0, label: 'J9[7]', identifier: Button1}
- {pin_num: '54', pin_signal: PTE2/SPI0_MISO, label: 'J9[5]', identifier: Button2}
- {pin_num: '55', pin_signal: PTG3, label: 'J9[15]', identifier: Led_3_Ora}
- {pin_num: '59', pin_signal: PTE1/SPI0_MOSI, label: 'J9[3]', identifier: Led_Fredda}
- {pin_num: '60', pin_signal: PTE0/SPI0_SCK/FTM1_CLK, label: 'J9[1]', identifier: Led_Calda}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
    BOARD_InitDEBUG_UARTPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '46', peripheral: KBI1, signal: 'P, 2', pin_signal: PTD2/KBI1_P2/SPI1_MISO, direction: INPUT, pullup_enable: enable, filter_selection: fltdiv3}
  - {pin_num: '5', peripheral: GPIOB, signal: 'GPIO, 7', pin_signal: PTE7/FTM2_CLK/FTM1_CH1, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '6', peripheral: GPIOB, signal: 'GPIO, 26', pin_signal: PTH2/BUSOUT/FTM1_CH0, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '14', peripheral: GPIOB, signal: 'GPIO, 25', pin_signal: PTH1/FTM2_CH1, direction: OUTPUT, gpio_init_state: 'true', high_drive_enable: disable}
  - {pin_num: '53', peripheral: GPIOB, signal: 'GPIO, 3', pin_signal: PTE3/SPI0_PCS0, direction: INPUT, pullup_enable: enable, filter_selection: no_init}
  - {pin_num: '54', peripheral: GPIOB, signal: 'GPIO, 2', pin_signal: PTE2/SPI0_MISO, direction: INPUT, pullup_enable: enable, filter_selection: no_init}
  - {pin_num: '42', peripheral: GPIOB, signal: 'GPIO, 9', pin_signal: PTF1, direction: OUTPUT}
  - {pin_num: '43', peripheral: GPIOB, signal: 'GPIO, 8', pin_signal: PTF0, direction: OUTPUT}
  - {pin_num: '55', peripheral: GPIOB, signal: 'GPIO, 19', pin_signal: PTG3, direction: OUTPUT}
  - {pin_num: '59', peripheral: GPIOB, signal: 'GPIO, 1', pin_signal: PTE1/SPI0_MOSI, direction: OUTPUT, high_drive_enable: disable}
  - {pin_num: '60', peripheral: GPIOB, signal: 'GPIO, 0', pin_signal: PTE0/SPI0_SCK/FTM1_CLK, direction: OUTPUT}
  - {pin_num: '27', peripheral: GPIOB, signal: 'GPIO, 15', pin_signal: PTF7/ADC0_SE15, direction: OUTPUT, gpio_init_state: 'false'}
  - {pin_num: '26', peripheral: GPIOA, signal: 'GPIO, 16', pin_signal: PTC0/FTM2_CH0/ADC0_SE8, direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{

    gpio_pin_config_t Start_Calda_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA16 (pin 26) */
    GPIO_PinInit(BOARD_INITPINS_Start_Calda_GPIO_PORT, BOARD_INITPINS_Start_Calda_PIN, &Start_Calda_config);

    gpio_pin_config_t Led_Calda_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB0 (pin 60) */
    GPIO_PinInit(BOARD_INITPINS_Led_Calda_GPIO_PORT, BOARD_INITPINS_Led_Calda_PIN, &Led_Calda_config);

    gpio_pin_config_t Led_Fredda_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB1 (pin 59) */
    GPIO_PinInit(BOARD_INITPINS_Led_Fredda_GPIO_PORT, BOARD_INITPINS_Led_Fredda_PIN, &Led_Fredda_config);

    gpio_pin_config_t Button2_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB2 (pin 54) */
    GPIO_PinInit(BOARD_INITPINS_Button2_GPIO_PORT, BOARD_INITPINS_Button2_PIN, &Button2_config);

    gpio_pin_config_t Button1_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB3 (pin 53) */
    GPIO_PinInit(BOARD_INITPINS_Button1_GPIO_PORT, BOARD_INITPINS_Button1_PIN, &Button1_config);

    gpio_pin_config_t PTE7_BLUE_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTB7 (pin 5) */
    GPIO_PinInit(BOARD_INITPINS_PTE7_BLUE_GPIO_PORT, BOARD_INITPINS_PTE7_BLUE_PIN, &PTE7_BLUE_config);

    gpio_pin_config_t Led_2_Ora_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB8 (pin 43) */
    GPIO_PinInit(BOARD_INITPINS_Led_2_Ora_GPIO_PORT, BOARD_INITPINS_Led_2_Ora_PIN, &Led_2_Ora_config);

    gpio_pin_config_t Led_1_Ora_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB9 (pin 42) */
    GPIO_PinInit(BOARD_INITPINS_Led_1_Ora_GPIO_PORT, BOARD_INITPINS_Led_1_Ora_PIN, &Led_1_Ora_config);

    gpio_pin_config_t Start_Fredda_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB15 (pin 27) */
    GPIO_PinInit(BOARD_INITPINS_Start_Fredda_GPIO_PORT, BOARD_INITPINS_Start_Fredda_PIN, &Start_Fredda_config);

    gpio_pin_config_t Led_3_Ora_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB19 (pin 55) */
    GPIO_PinInit(BOARD_INITPINS_Led_3_Ora_GPIO_PORT, BOARD_INITPINS_Led_3_Ora_PIN, &Led_3_Ora_config);

    gpio_pin_config_t PTH1_RED_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTB25 (pin 14) */
    GPIO_PinInit(BOARD_INITPINS_PTH1_RED_GPIO_PORT, BOARD_INITPINS_PTH1_RED_PIN, &PTH1_RED_config);

    gpio_pin_config_t PTH2_GREEN_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTB26 (pin 6) */
    GPIO_PinInit(BOARD_INITPINS_PTH2_GREEN_GPIO_PORT, BOARD_INITPINS_PTH2_GREEN_PIN, &PTH2_GREEN_config);
    /* High Current Drive Capability of PTE1: 0x00u */
    PORT_SetHighDriveEnable(PORT, kPORT_HighDrive_PTE1, false);
    /* High Current Drive Capability of PTH1: 0x00u */
    PORT_SetHighDriveEnable(PORT, kPORT_HighDrive_PTH1, false);
    /* Filter Selection for Input from KBI1: 0x03u */
    PORT_SetFilterSelect(PORT, kPORT_FilterKBI1, kPORT_FILTERDIV3); 
    /* Pull Enable for Port E Bit 2: 0x01u */
    PORT_SetPinPullUpEnable(PORT, kPORT_PTE, BOARD_INITPINS_Button2_PIN, true);
    /* Pull Enable for Port E Bit 3: 0x01u */
    PORT_SetPinPullUpEnable(PORT, kPORT_PTE, BOARD_INITPINS_Button1_PIN, true);
    /* Pull Enable for Port D Bit 2: 0x01u */
    PORT_SetPinPullUpEnable(PORT, kPORT_PTD, BOARD_INITPINS_Pulsante_PIN, true);

    SIM->SOPT = ((SIM->SOPT &
                  /* Mask bits to zero which are setting */
                  (~(SIM_SOPT_CLKOE_MASK)))

                 /* Bus Clock Output Enable: Bus clock output is disabled on PTH2. */
                 | SIM_SOPT_CLKOE(SOPT_CLKOE_0b0));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitLEDsPins:
- options: {coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '5', peripheral: GPIOB, signal: 'GPIO, 7', pin_signal: PTE7/FTM2_CLK/FTM1_CH1, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '6', peripheral: GPIOB, signal: 'GPIO, 26', pin_signal: PTH2/BUSOUT/FTM1_CH0, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '14', peripheral: GPIOB, signal: 'GPIO, 25', pin_signal: PTH1/FTM2_CH1, direction: OUTPUT, gpio_init_state: 'true'}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitLEDsPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitLEDsPins(void)
{

    gpio_pin_config_t PTE7_BLUE_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTB7 (pin 5) */
    GPIO_PinInit(BOARD_INITLEDSPINS_PTE7_BLUE_GPIO_PORT, BOARD_INITLEDSPINS_PTE7_BLUE_PIN, &PTE7_BLUE_config);

    gpio_pin_config_t PTH1_RED_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTB25 (pin 14) */
    GPIO_PinInit(BOARD_INITLEDSPINS_PTH1_RED_GPIO_PORT, BOARD_INITLEDSPINS_PTH1_RED_PIN, &PTH1_RED_config);

    gpio_pin_config_t PTH2_GREEN_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTB26 (pin 6) */
    GPIO_PinInit(BOARD_INITLEDSPINS_PTH2_GREEN_GPIO_PORT, BOARD_INITLEDSPINS_PTH2_GREEN_PIN, &PTH2_GREEN_config);

    SIM->SOPT = ((SIM->SOPT &
                  /* Mask bits to zero which are setting */
                  (~(SIM_SOPT_CLKOE_MASK)))

                 /* Bus Clock Output Enable: Bus clock output is disabled on PTH2. */
                 | SIM_SOPT_CLKOE(SOPT_CLKOE_0b0));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitTOUCHPins:
- options: {coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '23', peripheral: GPIOA, signal: 'GPIO, 30', pin_signal: PTD6/KBI1_P6/UART2_RX, direction: INPUT}
  - {pin_num: '22', peripheral: GPIOA, signal: 'GPIO, 31', pin_signal: PTD7/KBI1_P7/UART2_TX, direction: INPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitTOUCHPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitTOUCHPins(void)
{

    gpio_pin_config_t PTD6_TSI_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA30 (pin 23) */
    GPIO_PinInit(BOARD_INITTOUCHPINS_PTD6_TSI_GPIO_PORT, BOARD_INITTOUCHPINS_PTD6_TSI_PIN, &PTD6_TSI_config);

    gpio_pin_config_t PTD7_TSI_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA31 (pin 22) */
    GPIO_PinInit(BOARD_INITTOUCHPINS_PTD7_TSI_GPIO_PORT, BOARD_INITTOUCHPINS_PTD7_TSI_PIN, &PTD7_TSI_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitDEBUG_UARTPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '52', peripheral: UART1, signal: RX, pin_signal: PTC6/UART1_RX}
  - {pin_num: '51', peripheral: UART1, signal: TX, pin_signal: PTC7/UART1_TX}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitDEBUG_UARTPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitDEBUG_UARTPins(void)
{
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitACCELPins:
- options: {coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '47', peripheral: I2C0, signal: SCL, pin_signal: PTA3/KBI0_P3/UART0_TX/I2C0_SCL}
  - {pin_num: '48', peripheral: I2C0, signal: SDA, pin_signal: PTA2/KBI0_P2/UART0_RX/I2C0_SDA}
  - {pin_num: '44', peripheral: GPIOA, signal: 'GPIO, 28', pin_signal: PTD4/KBI1_P4}
  - {pin_num: '45', peripheral: GPIOA, signal: 'GPIO, 27', pin_signal: PTD3/KBI1_P3/SPI1_PCS0}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitACCELPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitACCELPins(void)
{
    /* pin 47,48 is configured as I2C0_SCL, I2C0_SDA */
    PORT_SetPinSelect(kPORT_I2C0, kPORT_I2C0_SCLPTA3_SDAPTA2);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitOSCPins:
- options: {coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '11', peripheral: OSC, signal: EXTAL, pin_signal: PTB7/I2C0_SCL/EXTAL}
  - {pin_num: '12', peripheral: OSC, signal: XTAL, pin_signal: PTB6/I2C0_SDA/XTAL}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitOSCPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitOSCPins(void)
{
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
